In [22]:
import numpy as np
a = np.array([[1,2,3,4],[2,3,4,5]], dtype = 'i1')

In [23]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=int8)

In [19]:
np.shape(a)

(2, 4)

In [20]:
b = a * 3

In [21]:
b

array([[ 3.,  6.,  9., 12.],
       [ 6.,  9., 12., 15.]])

In [29]:
dt = np.dtype([('age','i8')])
a = np.array([[1,2,3,4],[2,3,4,5]], dtype = dt)

In [32]:
print(a['age'])

[[1 2 3 4]
 [2 3 4 5]]


In [34]:
print(type(a))

<class 'numpy.ndarray'>


In [37]:
zeros_array = np.zeros((5),dtype = int)

In [38]:
zeros_array

array([0, 0, 0, 0, 0])

In [40]:
ones_array = np.ones((2,3), dtype = float)

In [41]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
with open('heights.txt','r') as f:
    data = f.read()
data = data.split(', ')
data = np.array(temp,dtype=int)


In [58]:
data * 0.0254

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [62]:
mangarange = np.arange(1,10,2)
mangarange1 = np.arange(1,10)
mangarange1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a = np.array([1,2,3,4,5,6,7])
a[-2:]

array([6, 7])

In [74]:
temp = np.array([
       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]
                                ])


In [75]:
np.shape(temp)

(2, 3, 4)

In [100]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [105]:
a[:,1:]
np.amax(a, axis=1)

array([ 3,  6,  9, 12])

In [86]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
a = a.reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
a + 3

array([[[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]],

       [[15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26]]])

In [92]:
c = a.reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [94]:
d = c.reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [96]:
temp1 = d[1,1,...]
temp1

array([16, 17, 18, 19])

In [98]:
temp2 = d[1,...,2]
temp2

array([14, 18, 22])

# Standard deviation
Mean = $\bar{x}$

Variance = $\frac{1}{n}\sum_{i=1}^n(x_{i}-\bar{x})^2$

Standard Deviation = $\sqrt{Variance}$

In [114]:
# Sample
array = np.array([10,7,4,9,15])
mean1 = np.mean(array)
print('Mean',mean1)
var1 = np.var(array)
print('Variance',var1)
std = np.sqrt(var1)
print('Standard Deviation',std)

Mean 9.0
Variance 13.2
Standard Deviation 3.63318042491699


In [120]:
# Peason Product

a = np.array([[1,4,6],[1,-4,-6]])
print(np.corrcoef(a[0],a[1]))

[[ 1.         -0.99186978]
 [-0.99186978  1.        ]]


In [122]:
a = np.arange(24)
matrix_3d = a.reshape(2,3,4)
print(matrix_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [124]:
cond = np.where(matrix_3d%2==0)

In [125]:
print(cond)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2], dtype=int64))


In [127]:
print(matrix_3d[cond])

[ 0  2  4  6  8 10 12 14 16 18 20 22]
