Cho tập tin heights_1.txt, weights_1.txt => hãy chép dữ liệu từ tập tin
này vào list là height, weight
1. Chuyển list height thành numpy array np_height => In shape của np_height
2. Chuyển list weight thành numpy array np_weight => In shape của np_weight
3. Cho hệ số quy đổi từ inch sang m là 0.0254 => Hãy tạo ra numpy array np_height_m dựa trên
công thức: np_height * hệ số quy đổi này => In kết quả
4. Cho hệ số quy đổi từ pound sang kg là 0.453592 => Hãy tạo ra numpy array np_weight_kg
dựa trên công thức: np_weight * hệ số quy đổi này => In kết quả
5. Tính và in BMI của np_height_m và np_weight_kg theo công thức BIM = Cân nặng / (Chiều
cao * Chiều cao)
6. In weight ở vị trí index 50
7. In ra array con lấy từ index 100 đến index 110 (lấy cả index 110)


In [1]:
import numpy as np

In [2]:
with open('heights_1.txt','r') as f:
    data_h = f.read()

with open('weights_1.txt','r') as f:
    data_w = f.read()

In [3]:
#1. Chuyển list height thành numpy array np_height => In shape của np_height
#2. Chuyển list weight thành numpy array np_weight => In shape của np_weight

heights = np.array(data_h.split(', '),int)
weights = np.array(data_w.split(', '),int)

In [4]:
print('Heights:',heights)
print('Shape Heights:',np.shape(heights))

Heights: [74 74 72 ... 75 75 73]
Shape Heights: (1015,)


In [5]:
print('Weights:',weights)
print('Shape Weights:',np.shape(weights))

Weights: [180 215 210 ... 205 190 195]
Shape Weights: (1015,)


In [6]:
# 3. Cho hệ số quy đổi từ inch sang m là 0.0254 => Hãy tạo ra numpy array np_height_m dựa trên
# công thức: np_height * hệ số quy đổi này => In kết quả
np_height_m = heights * 0.0254

In [7]:
np_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [8]:
# 4. Cho hệ số quy đổi từ pound sang kg là 0.453592 => Hãy tạo ra numpy array np_weight_kg
# dựa trên công thức: np_weight * hệ số quy đổi này => In kết quả

np_weight_kg = weights * 0.453592
np_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [9]:
# 5. Tính và in BMI của np_height_m và np_weight_kg theo công thức BIM = Cân nặng / (Chiều
# cao * Chiều cao)
BIM = np_weight_kg / (np_height_m ** 2)
BIM

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

In [10]:
#6. In weight ở vị trí index 50
print(weights[50])

200


In [11]:
#7. In ra array con lấy từ index 100 đến index 110 (lấy cả index 110)
array_con = BIM[100:111]
array_con

array([29.02517946, 29.52992539, 24.41211827, 29.02517946, 26.58105883,
       24.41211827, 22.42854777, 26.24790956, 26.87285979, 26.38652678,
       28.88767328])