1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ
thay bằng 100 => in kết quả
4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng
np.intersect1d(a,b)
5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a,
dùng np.setdiff1d(a,b)
6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
8. Tạo array có giá trị từ 10 đến 24
9. Cho array k => tạo array l từ k với các phần tử đếu khác 0
10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
12. Từ array của câu trên, xóa phần tử index = 0, 1, 2

In [1]:
import numpy as np

In [2]:
# 1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
array0_9 = np.arange(0,10)
print(array0_9)
print(type(array0_9))
print(array0_9.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [3]:
#2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
arr_odd = array0_9[array0_9%2!=0]
print("Odd Array",arr_odd)
arr_even = array0_9[array0_9%2==0]
print("Even Array",arr_even)

Odd Array [1 3 5 7 9]
Even Array [0 2 4 6 8]


In [4]:
# 3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ
# thay bằng 100 => in kết quả
condition = np.where(array0_9 % 2 != 0,100,array0_9)
condition

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

In [5]:
# 4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng
# np.intersect1d(a,b)
array_1 = np.arange(0,10)
print('Array_1: ', array_1)
array_2 = np.arange(5,16)
print('Array_2: ', array_2)
array_intersec = np.intersect1d(array_1, array_2)
print('Intersect 2 Array: ',array_intersec)

Array_1:  [0 1 2 3 4 5 6 7 8 9]
Array_2:  [ 5  6  7  8  9 10 11 12 13 14 15]
Intersect 2 Array:  [5 6 7 8 9]


In [6]:
# 5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a,
# dùng np.setdiff1d(a,b)
array_only_a = np.setdiff1d(array_1, array_2)
print('Only a: ', array_only_a)

Only a:  [0 1 2 3 4]


In [7]:
# 6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
array_e = np.arange(0,15)
cond = np.where((array_e >= 5) &( array_e < 11))
array_f = array_e[cond]
array_f

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# 7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
array_0 = np.zeros((10,))
array_0[4] = 1
array_0

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
# 8. Tạo array có giá trị từ 10 đến 24
array_10_24 = np.arange(10,25)
array_10_24

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
# 9. Cho array k => tạo array l từ k với các phần tử đếu khác 0
array_k = np.array([0,10,6,8,0,4,9,12])
print(array_k)
cond = np.where(array_k!=0)
print(cond)
array_l = array_k[cond]
array_l

[ 0 10  6  8  0  4  9 12]
(array([1, 2, 3, 5, 6, 7]),)


array([10,  6,  8,  4,  9, 12])

In [11]:
# 10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
array_temp = np.append(array_l,[10,20])
array_temp

array([10,  6,  8,  4,  9, 12, 10, 20])

In [12]:
# 11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
array_temp = np.insert(array_temp,5,100)
array_temp

array([ 10,   6,   8,   4,   9, 100,  12,  10,  20])

In [13]:
# 12. Từ array của câu trên, xóa phần tử index = 0, 1, 2
array_12 = np.delete(array_temp,[0,1,2])
array_12

array([  4,   9, 100,  12,  10,  20])