1. Tạo array 3x3 với tất cả các giá trị đều là True. In array
2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang
cột 3 và ngược lại. => In array
3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có
giá trị rỗng nào không?
7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0

In [49]:
import numpy as np
array_3x3 = np.full((3,3),True)
array_3x3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# 2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang
# cột 3 và ngược lại. => In array
array_1D = np.arange(0,9)
print('Array 1D: ',array_1D)
array_2D = np.reshape(array_1D,(3,3))
print('Array 2D:\n',array_2D)
# Chuyển cột một sang cột 3 và ngược lại
array_2D[:,0], array_2D[:,2] = array_2D[:,2], array_2D[:,0].copy()
print('Array 2D after swap column 1,3: \n',array_2D)

Array 1D:  [0 1 2 3 4 5 6 7 8]
Array 2D:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array 2D after swap column 1,3: 
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [51]:
# 3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
array_2D[0,:], array_2D[1,:] = array_2D[1,:], array_2D[0,:].copy()
print('Array 2D after swap row 1 ,2:\n',array_2D)

Array 2D after swap row 1 ,2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [52]:
#4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
# array_2D = np.flip(array_2D, axis=0)
array_2D = array_2D[::-1]
print('Array 2D after reverse row \n', array_2D)

Array 2D after reverse row 
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [55]:
# 5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
array_2D = array_2D[:,::-1]
array_2D

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [66]:
# 6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có
# giá trị rỗng nào không?
h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
if np.isnan(np.min(h)):
    print('Existed')


Existed


In [68]:
# 7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0
array_7 = np.where(np.isnan(h),0,h)
print('Array_7:\n',array_7)

Array_7:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
